spring:
  cache:
    cache-names: goodcache
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=1d
    redis:
      key-prefix: "spring:cache::"
    type: caffeine
  application:
    name: demo
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    hikari:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: 'jdbc:hsqldb:hsql://121.36.231.91/ncc'
    username: SA
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      show-sql: true
    database: hsql
  redis:
    host: 121.36.231.91
    password: BIP####1234
logging:
#  config: classpath:log4j2-spring.xml
  level:
    root: INFO
    org.springframework.web: trace
    io.netty: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: trace
  pattern:
#    dateformat: yyyy-MM-dd
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'

