spring:
  cache:
    cache-names: goodcache
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=1d
  application:
    name: demo
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    hikari:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: 'jdbc:hsqldb:hsql://121.36.231.91/ncc'
    username: SA
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      show-sql: true
    database: hsql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
